Freyj/Fluffy-Hero-Maker

cli_main.py
databases/dnd5_backgrounds.py
dnd5_character/DnD5Background.py
dnd5_character/DnD5Race.py
dnd_character_creator.py

Solving display issue from #7 
cleaning up some of the code

Cleanup of display

---

databases/data/spells/srd_lvl_1.json
databases/dnd5_spell_db.py
dnd_character_creator.py

Solves issue #17  (and another that hadn't been seen at this moment, that import from db failed)

Spell bug fix

---

databases/data/classes/srd_classes.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd_character_creator.py

Display the class features in Class choice and in Character Recap
Solves #16 for class features without any player choice

Display the class features

---

utils/dice_roller.py

Correcting bug fix of die roll

---

dnd5_character/DnD5Race.py

Removing old debug print

---

characters/dnd5.py
databases/data/classes/srd_classes.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd5_character/DnD5Race.py
utils/templates/class_template.json

Adding tool proficiency addition from class and to template
Work for #24

Adding Rogue class

---

characters/dnd5.py
dnd5_character/DnD5Race.py
dnd_character_creator.py

Hit point calculation

---

characters/dnd5.py
databases/data/classes/srd_classes.json
dnd5_character/DnD5Race.py

minor update of display 
minor change to save json file with hit points
#24

Adding Barbarian to  classes

---

databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd_character_creator.py

display and choice
fixes #22 and #32

Adding class feature choice

---

characters/dnd5.py
databases/data/classes/srd_classes.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd_character_creator.py

Adding Saving Throws proficiencies from class

---

databases/dnd5_backgrounds.py
databases/dnd5_classes_db.py
databases/dnd5_languages_db.py
databases/dnd5_monster_db.py

Correcting doubling of information in database

---

databases/data/classes/srd_classes.json
databases/data/races/srd.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
utils/templates/class_template.json

* minor update of Hill Dwarf for missing dot
* update of class template to have saving throw proficiency
#24

Addition of Paladin class

---

databases/data/classes/srd_classes.json

Adding Monk Class

---

databases/dnd5_backgrounds.py
dnd5_character/DnD5Background.py
dnd_character_creator.py

Cleaning up background display

---

characters/dnd5.py
databases/dnd5_monster_db.py
utils/utilities.py

Can now generate stats that go no higher than +7 total bonus and no lower than +3
Solves #6

Adding missing generation type 5

---

dnd_character_creator.py

Background last fix

---

README.md
databases/data/monsters/srd_celestial.json
utils/templates/monster_template.json

* added Unicorn, Solar, Pegasus
* updated monster template to have only one element and not the array (easier to copy/paste)
* updated the readme a little bit
#3

Adding Celestials

---

characters/dnd5.py
databases/dnd5_backgrounds.py
databases/dnd5_classes_db.py
databases/dnd5_monster_db.py
databases/dnd5_races_db.py
dnd5_character/DnD5Background.py
dnd5_character/DnD5Class.py
dnd5_character/DnD5Race.py
dnd5_monsters/dnd5_monster.py
dnd_character_creator.py
dnd_monster_stat_display.py
dnd_spell_display.py
utils/utilities.py

* Switching to str.join instead of custom function (utils.list_to_str)
* better saving of racial traits choices to solve dragonborn bad display
solves #55 and cleans #34

Code improvement

---

databases/data/spells/srd_cantrips.json
databases/data/spells/srd_lvl_1.json
databases/data/spells/srd_lvl_9.json
databases/dnd5_spell_db.py
dnd5_character/DnD5Spell.py
dnd_spell_display.py
utils/templates/spell_template.json

* Adding class info in object and database
* adding function to get spells from class
* Get spells by class and level
* add class info for cantrips and lvl 1 and 9  spells
#53

Add classes array in json files and template

---

dnd5_character/DnD5Race.py

Remove excess linebreak

---

cli_main.py
databases/data/classes/srd_classes.json
databases/db_populate.py
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd_character_creator.py
dnd_monster_stat_display.py
dnd_spell_display.py
utils/templates/class_template.json

detected small bug with monster display, deactivated db populate
#24

Adding Wizard class

---

databases/data/classes/srd_classes.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
utils/templates/class_template.json

* adding forgotten spell slots from class
* Updating template for class
Closes #73 
and updates #24

Adding Sorcerer

---

databases/data/classes/srd_classes.json
dnd5_character/DnD5Class.py

Add Cleric class

---

.gitignore
databases/dnd5_languages_db.py
tests/test_languages_db.py

Correct bug from druidic language

---

databases/data/classes/srd_classes.json
databases/dnd5_classes_db.py
dnd5_character/DnD5Class.py
dnd_character_creator.py

Should solve #75 
Cleaned up database values

Feature bug

---

databases/data/classes/srd_classes.json
dnd5_character/DnD5Class.py

Adding Ranger class

---

databases/data/classes/srd_classes.json

Added Warlock

---

databases/data/monsters/srd_celestial.json

Fix action/description and traits/effets keys in json

---

databases/data/monsters/srd_celestial.json
dnd5_monsters/dnd5_monster.py
dnd_monster_stat_display.py
utils/utilities.py

Implementation of cli_display in monster class

---

characters/DnD5Character.py
characters/character.py
databases/db_populate.py
databases/dnd5/dnd5_backgrounds.py
databases/dnd5/dnd5_classes_db.py
databases/dnd5/dnd5_db.py
databases/dnd5/dnd5_languages_db.py
databases/dnd5/dnd5_monster_db.py
databases/dnd5/dnd5_races_db.py
databases/dnd5/dnd5_spell_db.py
dnd5_character/DnD5Background.py
dnd5_character/DnD5Race.py
dnd5_character/DnD5Spell.py
dnd5_monster/DnD5Monster.py
dnd_character_creator.py
dnd_monster_stat_display.py
dnd_spell_display.py
tests/test_dice_roller.py
tests/test_languages_db.py
utils/dice_roller.py

* moved dnd5 databases files to a specific folder
* cleaned up some class and file names that were not consistent
* adding some documentation for functions (In Progress)
some work on #66

Improve code documentation

---

.travis.yml
README.md
app/main_flask.py
requirements.txt
utils/jinja_templates/allMonstersList.html
utils/jinja_templates/allSpellsList.html
utils/jinja_templates/dndMonster.html
utils/jinja_templates/dndSpell.html
utils/jinja_templates/home.html

* route /random-dnd-spell to display a random spell and its informations
* route /random-dnd-monster displays a random monster and its informations
* route /all-dnd-monsters displays the list of monsters in the database
* route /all-dnd-spells displays the list of spells in the database
* route / displays a home page with links to previous routes
* links to specific monster/spell from the list pages
* updated requirements.txt with Flask
* first jinja2 templates
* adding FLASK_APP environment variable for travis
Beginning work for #36 in a way

Adding internal http server with flask

---

README.md
app/main_flask.py
characters/DnD5Character.py
utils/jinja_templates/dndCharacter.html
utils/jinja_templates/dndMonster.html

* the route `/dnd-random-character-gen/<name>` displays a randomly generated character with class and background picked, and some more details such as stats and racial traits.

adding random dnd character generation page

---

app/static/style.css
dnd5_character/DnD5Spell.py
dnd_spell_display.py
utils/jinja_templates/dndSpell.html

Solves #90, and offers better spell display

Spell display

---

README.md
app/main_flask.py
app/static/style.css
characters/DnD5Character.py
traveller/CTCharacter.py
traveller/funcs_ct.py
traveller/gen_ct_char.py
utils/jinja_templates/ctCharacter.html
utils/jinja_templates/home.html

Also adding flask display of the random character
Closes #108

Adding random character generation for CT

---

traveller/CTCharacter.py
traveller/funcs_ct.py
traveller/gen_ct_char.py
utils/jinja_templates/ctCharacter.html

Added information that the character had died on the page (slightly important >_>)
closes #110  for now

Corrected error of negative stats

---

app/main_flask.py
requirements.txt
traveller/demo.yml
traveller/gen_ct_char.py
utils/jinja_templates/ctCharacter.html

* Fixing template name
* save file is no longer by default for traveller cli generation
* adding sty requirements
* minor , removed from classic traveller template

Hot fix for failed template name

---

utils/jinja_templates/home.html

Fixes forgotten link for party

Forgotten link

---

README.md
app/main_flask.py
app/static/ctCharacter.js
traveller/CTCharacter.py
utils/jinja_templates/ctCharacter.html
utils/utilities.py

Exports character info to a json file
#117

Adding export to json for ct traveller

---

traveller/CTCharacter.py
traveller/gen_ct_char.py

* on random gen, older characters more likely to refuse to reenlist
* adding a forgotten history line for the choice of leaving a service
Closes #121

Choosing to leave service function of age

---

README.md
app/main_flask.py
traveller/CTCharacter.py
traveller/gen_ct_char.py

Add a route to get one character that survived his career

---

utils/jinja_templates/classic_traveller/ctCharacter.html
utils/jinja_templates/classic_traveller/ctParty.html
utils/jinja_templates/dnd5/dndAllMonstersList.html
utils/jinja_templates/dnd5/dndAllSpellsList.html
utils/jinja_templates/dnd5/dndCharacter.html
utils/jinja_templates/dnd5/dndMonster.html
utils/jinja_templates/dnd5/dndSpell.html

Correcting the super large buttons and their positions

Adding a home button on all pages

---

traveller/CTCharacter.py
traveller/gen_ct_char.py

* adding commission and promotion information at term
* added UPP display before choosing service to roll for
* added cash benefit gained
* added printed info in case of improved weapon skill during benefits (only when not doing an automatic gen

Added printed info for ct char gen

---

utils/jinja_templates/classic_traveller/base_ct.html
utils/jinja_templates/classic_traveller/ctCharacter.html
utils/jinja_templates/classic_traveller/ctParty.html
utils/jinja_templates/dnd5/base_dnd.html
utils/jinja_templates/dnd5/dndAllMonstersList.html
utils/jinja_templates/dnd5/dndAllSpellsList.html
utils/jinja_templates/dnd5/dndCharacter.html
utils/jinja_templates/dnd5/dndMonster.html
utils/jinja_templates/dnd5/dndSpell.html
utils/jinja_templates/home.html

Added base template for dnd pages and ct pages

Jinja base templating

---

traveller/CTCharacter.py

On the classic traveller character generation, a character could end up with stats over 15 which is not possible for humans.
This pull request fixes that.

Stats cannot go over 15 now
